### PR TITLE
Armando/grwth 3412 add erc721c info to the collection stats

### PR DESCRIPTION
**Pull request by r3lays**

### CODE REVIEW

**Review by pedromcunha — APPROVED** [review]

**Comment by ted-palmer** [comment]
Should update on the token page as well

**Comment by r3lays** [comment]
Doesn't that use the token details component?

**Comment by ted-palmer** [comment]
No, I believe it uses the `TokenInfo` component. I also think we should change the format to `ERC721-C` instead of `ERC721c`. What do y'all think @pedromcunha @r3lays

**Comment by r3lays** [comment]
#351 
`I also think we should change the format to ERC721-C instead of ERC721c.` What does OpenSea do? I thought I saw somewhere we had lowercase.

**Comment by ted-palmer** [comment]
Looks like opensea just displays `ERC-721`

**Comment by r3lays** [comment]
Interesting...so why are we even displaying it at all? CC @lunarmayor thoughts?

**Comment by r3lays** [comment]
Could you share the collection @ted-palmer?

**Comment by ted-palmer** [comment]
Sure, it's the SICK collection on polygon: `0xf201b9422c705f86d409c78cd44bfdd1877d4ba7`

**Comment by r3lays** [comment]
Thanks, also I agree with you on the display changes. Looks a little funky.
Screenshot 2023-10-17 at 12 50 06 PM

**Pull request merged**
